sudo: required
services:
    -docker

before_install:
    docker build -t dockerlearn -f Dockerfile.dev .

script:
    docker run -e CI=true dockerlearn npm run test


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-learn"
  env: "dockerlearn-env"
  bucket_name: "elasticbeanstalk-us-east-1-830036975273"
  bucket_path: "docker-learning"
  on:
    branch: main